_format_version: "3.0"
_workspace: pet_store
consumers:
- basicauth_credentials:
  - password: 35984ed7d8949e987b6ad43987d1a2e3e7066e55
    username: vendor
  jwt_secrets:
  - algorithm: HS256
    key: new_vendor
    secret: auto
  keyauth_credentials:
  - key: ven@apikey
  username: Vendor
plugins:
- config:
    anonymous: null
    hide_credentials: true
  enabled: false
  name: basic-auth
  protocols:
  - grpc
  - grpcs
  - http
  - https
  - ws
  - wss
- config:
    content_type: application/json
    custom_fields_by_lua: {}
    flush_timeout: 2
    headers: {}
    http_endpoint: http://172.16.20.71:9010
    keepalive: 60000
    method: POST
    queue_size: 1
    retry_count: 10
    timeout: 10000
  enabled: true
  name: http-log
  protocols:
  - grpc
  - grpcs
  - http
  - https
- config:
    anonymous: null
    claims_to_verify:
    - exp
    cookie_names: []
    header_names:
    - authorization
    key_claim_name: iss
    maximum_expiration: 0
    run_on_preflight: true
    secret_is_base64: false
    uri_param_names:
    - jwt
  enabled: false
  name: jwt
  protocols:
  - grpc
  - grpcs
  - http
  - https
- config:
    anonymous: null
    hide_credentials: false
    key_in_body: false
    key_in_header: true
    key_in_query: true
    key_names:
    - apikey
    run_on_preflight: true
  enabled: false
  name: key-auth
  protocols:
  - grpc
  - grpcs
  - http
  - https
  - ws
  - wss
- config:
    accept_http_if_already_terminated: false
    anonymous: null
    auth_header_name: authorization
    enable_authorization_code: true
    enable_client_credentials: false
    enable_implicit_grant: false
    enable_password_grant: false
    global_credentials: false
    hide_credentials: false
    mandatory_scope: false
    persistent_refresh_token: false
    pkce: lax
    provision_key: key
    refresh_token_ttl: 1209600
    reuse_refresh_token: false
    scopes:
    - email
    token_expiration: 7200
  enabled: false
  name: oauth2
  protocols:
  - grpc
  - grpcs
  - http
  - https
  - ws
  - wss
- config:
    bandwidth_metrics: true
    latency_metrics: true
    per_consumer: true
    status_code_metrics: true
    upstream_health_metrics: true
  enabled: true
  name: prometheus
  protocols:
  - grpc
  - grpcs
  - http
  - https
- config:
    day: null
    error_code: 429
    error_message: API rate limit exceeded
    fault_tolerant: true
    header_name: null
    hide_client_headers: false
    hour: 100
    limit_by: consumer
    minute: 5
    month: null
    path: null
    policy: local
    redis_database: 0
    redis_host: null
    redis_password: null
    redis_port: 6379
    redis_server_name: null
    redis_ssl: false
    redis_ssl_verify: false
    redis_timeout: 2000
    redis_username: null
    second: null
    year: null
  enabled: false
  name: rate-limiting
  protocols:
  - grpc
  - grpcs
  - http
  - https
services:
- connect_timeout: 60000
  enabled: true
  host: petstore3.swagger.io
  name: Pet_Service
  path: /api/v3
  plugins:
  - config:
      bandwidth_metrics: true
      latency_metrics: true
      per_consumer: true
      status_code_metrics: true
      upstream_health_metrics: true
    enabled: true
    name: prometheus
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - POST
    name: addPet
    path_handling: v0
    paths:
    - ~/pet$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - POST
    name: createUser
    path_handling: v0
    paths:
    - ~/user$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - POST
    name: createUserInput
    path_handling: v0
    paths:
    - ~/user/createWithList$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - DELETE
    name: deleteOrder
    path_handling: v0
    paths:
    - ~/store/order/(?<orderId>[^/]+)$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - DELETE
    name: deletePet
    path_handling: v0
    paths:
    - ~/pet/(?<petId>[^/]+)$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - DELETE
    name: deleteUser
    path_handling: v0
    paths:
    - ~/user/(?<username>[^/]+)$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - GET
    name: findPetStatus
    path_handling: v0
    paths:
    - ~/pet/findByStatus$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - GET
    name: findPetTags
    path_handling: v0
    paths:
    - ~/pet/findByTags$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - GET
    name: getInvent
    path_handling: v0
    paths:
    - ~/store/inventory$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - GET
    name: getOrderId
    path_handling: v0
    paths:
    - ~/store/order/(?<orderId>[^/]+)$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - GET
    name: getPetById
    path_handling: v0
    paths:
    - ~/pet/(?<petId>[^/]+)$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - GET
    name: getUserName
    path_handling: v0
    paths:
    - ~/user/(?<username>[^/]+)$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - GET
    name: loginUser
    path_handling: v0
    paths:
    - ~/user/login$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - GET
    name: logoutUser
    path_handling: v0
    paths:
    - ~/user/logout$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - POST
    name: placeOrder
    path_handling: v0
    paths:
    - ~/store/order$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - PUT
    name: updatePet
    path_handling: v0
    paths:
    - ~/pet$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - POST
    name: updatePetForm
    path_handling: v0
    paths:
    - ~/pet/(?<petId>[^/]+)$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - PUT
    name: updateUser
    path_handling: v0
    paths:
    - ~/user/(?<username>[^/]+)$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  - https_redirect_status_code: 426
    methods:
    - POST
    name: uploadFile
    path_handling: v0
    paths:
    - ~/pet/(?<petId>[^/]+)/uploadImage$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - OAS3_import
  tags:
  - OAS3_import
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: httpbin.org
  name: stage
  path: /anything
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: http-test1
    path_handling: v0
    paths:
    - /test
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  - https_redirect_status_code: 426
    name: httpbin-test
    path_handling: v0
    paths:
    - /test
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: httpbin.org
  name: test1
  path: /anything
  plugins:
  - config:
      anonymous: null
      audience: null
      audience_claim:
      - aud
      audience_required: null
      auth_methods:
      - bearer
      - session
      authenticated_groups_claim: null
      authorization_cookie_domain: null
      authorization_cookie_httponly: true
      authorization_cookie_lifetime: 600
      authorization_cookie_name: authorization
      authorization_cookie_path: /
      authorization_cookie_samesite: "off"
      authorization_cookie_secure: null
      authorization_endpoint: null
      authorization_query_args_client: null
      authorization_query_args_names: null
      authorization_query_args_values: null
      bearer_token_cookie_name: null
      bearer_token_param_type:
      - header
      - query
      - body
      by_username_ignore_case: false
      cache_introspection: true
      cache_token_exchange: true
      cache_tokens: true
      cache_tokens_salt: UjU4pHkKDHPg8SGhYoXvHqMgP0jZmLVV
      cache_ttl: 3600
      cache_ttl_max: null
      cache_ttl_min: null
      cache_ttl_neg: null
      cache_ttl_resurrect: null
      cache_user_info: true
      client_alg: null
      client_arg: client_id
      client_auth: null
      client_credentials_param_type:
      - header
      - query
      - body
      client_id:
      - f8929dbf-e55a-4d26-9fd0-f44ef4adad61
      client_jwk: null
      client_secret:
      - BSI8Q~8BketbtT3HvqvyBaWwA_JMwKqdh-c4HdgC
      consumer_by:
      - custom_id
      consumer_claim:
      - azp
      consumer_optional: false
      credential_claim:
      - sub
      disable_session: null
      discovery_headers_names: null
      discovery_headers_values: null
      display_errors: true
      domains: null
      downstream_access_token_header: null
      downstream_access_token_jwk_header: null
      downstream_headers_claims: null
      downstream_headers_names: null
      downstream_id_token_header: null
      downstream_id_token_jwk_header: null
      downstream_introspection_header: null
      downstream_introspection_jwt_header: null
      downstream_refresh_token_header: null
      downstream_session_id_header: null
      downstream_user_info_header: null
      downstream_user_info_jwt_header: null
      enable_hs_signatures: false
      end_session_endpoint: null
      extra_jwks_uris: null
      forbidden_destroy_session: true
      forbidden_error_message: Forbidden
      forbidden_redirect_uri: null
      groups_claim:
      - groups
      groups_required: null
      hide_credentials: false
      http_proxy: null
      http_proxy_authorization: null
      http_version: 1.1
      https_proxy: null
      https_proxy_authorization: null
      id_token_param_name: null
      id_token_param_type:
      - header
      - query
      - body
      ignore_signature: []
      introspect_jwt_tokens: false
      introspection_accept: application/json
      introspection_check_active: true
      introspection_endpoint: null
      introspection_endpoint_auth_method: null
      introspection_headers_client: null
      introspection_headers_names: null
      introspection_headers_values: null
      introspection_hint: access_token
      introspection_post_args_client: null
      introspection_post_args_names: null
      introspection_post_args_values: null
      issuer: https://login.microsoftonline.com/9ec3c97f-27a8-456a-b12e-f5624d2adf15/v2.0
      issuers_allowed: null
      jwt_session_claim: sid
      jwt_session_cookie: null
      keepalive: true
      leeway: 0
      login_action: upstream
      login_methods:
      - authorization_code
      login_redirect_mode: fragment
      login_redirect_uri: null
      login_tokens:
      - id_token
      logout_methods:
      - POST
      - DELETE
      logout_post_arg: null
      logout_query_arg: null
      logout_redirect_uri: null
      logout_revoke: false
      logout_revoke_access_token: true
      logout_revoke_refresh_token: true
      logout_uri_suffix: null
      max_age: null
      no_proxy: null
      password_param_type:
      - header
      - query
      - body
      preserve_query_args: false
      redirect_uri: null
      rediscovery_lifetime: 30
      refresh_token_param_name: null
      refresh_token_param_type:
      - header
      - query
      - body
      refresh_tokens: true
      resolve_distributed_claims: false
      response_mode: query
      response_type:
      - code
      reverify: false
      revocation_endpoint: null
      revocation_endpoint_auth_method: null
      roles_claim:
      - roles
      roles_required: null
      run_on_preflight: true
      scopes:
      - openid
      scopes_claim:
      - scope
      scopes_required: null
      search_user_info: false
      session_compressor: none
      session_cookie_domain: null
      session_cookie_httponly: true
      session_cookie_idletime: null
      session_cookie_lifetime: 3600
      session_cookie_maxsize: 4000
      session_cookie_name: session
      session_cookie_path: /
      session_cookie_renew: 600
      session_cookie_samesite: Lax
      session_cookie_secure: null
      session_memcache_host: 127.0.0.1
      session_memcache_port: 11211
      session_memcache_prefix: sessions
      session_memcache_socket: null
      session_redis_cluster_maxredirections: null
      session_redis_cluster_nodes: null
      session_redis_connect_timeout: null
      session_redis_host: 127.0.0.1
      session_redis_password: null
      session_redis_port: 6379
      session_redis_prefix: sessions
      session_redis_read_timeout: null
      session_redis_send_timeout: null
      session_redis_server_name: null
      session_redis_socket: null
      session_redis_ssl: false
      session_redis_ssl_verify: false
      session_redis_username: null
      session_secret: null
      session_storage: cookie
      session_strategy: default
      ssl_verify: false
      timeout: 10000
      token_endpoint: null
      token_endpoint_auth_method: null
      token_exchange_endpoint: null
      token_headers_client: null
      token_headers_grants: null
      token_headers_names: null
      token_headers_prefix: null
      token_headers_replay: null
      token_headers_values: null
      token_post_args_client: null
      token_post_args_names: null
      token_post_args_values: null
      unauthorized_error_message: Unauthorized
      unauthorized_redirect_uri: null
      unexpected_redirect_uri: null
      upstream_access_token_header: authorization:bearer
      upstream_access_token_jwk_header: null
      upstream_headers_claims: null
      upstream_headers_names: null
      upstream_id_token_header: null
      upstream_id_token_jwk_header: null
      upstream_introspection_header: null
      upstream_introspection_jwt_header: null
      upstream_refresh_token_header: null
      upstream_session_id_header: null
      upstream_user_info_header: null
      upstream_user_info_jwt_header: null
      userinfo_accept: application/json
      userinfo_endpoint: null
      userinfo_headers_client: null
      userinfo_headers_names: null
      userinfo_headers_values: null
      userinfo_query_args_client: null
      userinfo_query_args_names: null
      userinfo_query_args_values: null
      verify_claims: true
      verify_nonce: true
      verify_parameters: false
      verify_signature: true
    enabled: true
    name: openid-connect
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
