_format_version: "3.0"
_workspace: Thejas_Kong
consumer_groups:
- name: team
consumers:
- hmacauth_credentials:
  - secret: secret
    username: alice123
  username: alice
- hmacauth_credentials:
  - secret: thejas
    username: thejas123
  jwt_secrets:
  - algorithm: HS256
    key: LY5a3yo0qJ8aeHS69BR1xpA11T6FRjzn
    secret: thejas
  keyauth_credentials:
  - key: alice123
  username: thejas
plugins:
- config:
    day: null
    error_code: 429
    error_message: API rate limit exceeded
    fault_tolerant: true
    header_name: null
    hide_client_headers: false
    hour: null
    limit_by: consumer
    minute: null
    month: null
    path: null
    policy: local
    redis_database: 0
    redis_host: null
    redis_password: null
    redis_port: 6379
    redis_server_name: null
    redis_ssl: false
    redis_ssl_verify: false
    redis_timeout: 2000
    redis_username: null
    second: 30
    year: null
  consumer: thejas
  enabled: false
  name: rate-limiting
  protocols:
  - grpc
  - grpcs
  - http
  - https
  service: RateLimitService
services:
- connect_timeout: 60000
  enabled: true
  host: httpbin.org
  name: DemoService
  path: /json
  plugins:
  - config:
      auto_approve: false
      description: null
      display_name: requestapp
      show_issuer: false
    enabled: false
    name: application-registration
    protocols:
    - grpc
    - grpcs
    - http
    - https
  - config:
      algorithms:
      - hmac-sha1
      - hmac-sha256
      - hmac-sha384
      - hmac-sha512
      anonymous: null
      clock_skew: 300
      enforce_headers:
      - date, request-line, host
      hide_credentials: false
      validate_request_body: false
    enabled: false
    name: hmac-auth
    protocols:
    - grpc
    - grpcs
    - http
    - https
    - ws
    - wss
  - config:
      anonymous: null
      claims_to_verify: null
      cookie_names: []
      header_names:
      - authorization
      key_claim_name: iss
      maximum_expiration: 0
      run_on_preflight: true
      secret_is_base64: false
      uri_param_names:
      - jwt
    enabled: false
    name: jwt
    protocols:
    - grpc
    - grpcs
    - http
    - https
  - config:
      anonymous: null
      hide_credentials: false
      key_in_body: false
      key_in_header: true
      key_in_query: true
      key_names:
      - apikey
      run_on_preflight: true
    enabled: false
    name: key-auth
    protocols:
    - grpc
    - grpcs
    - http
    - https
    - ws
    - wss
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - GET
    - HEAD
    name: DemoRoute
    path_handling: v0
    paths:
    - /headers
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: httpbin.org
  name: OIDC_Service
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: OIDC_Route
    path_handling: v0
    paths:
    - /oidc
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: httpbin.org
  name: RateLimitService
  path: /anything
  plugins:
  - config:
      anonymous: null
      hide_credentials: false
      key_in_body: false
      key_in_header: true
      key_in_query: true
      key_names:
      - apikey
      run_on_preflight: true
    enabled: false
    name: key-auth
    protocols:
    - grpc
    - grpcs
    - http
    - https
    - ws
    - wss
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: RateLimitRoute
    path_handling: v0
    paths:
    - /ratelimit
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: httpbin.org
  name: example-service
  path: /json
  plugins:
  - config:
      algorithms:
      - hmac-sha1
      - hmac-sha256
      - hmac-sha384
      - hmac-sha512
      anonymous: null
      clock_skew: 300
      enforce_headers:
      - date
      - request-line
      - host
      hide_credentials: false
      validate_request_body: false
    enabled: false
    name: hmac-auth
    protocols:
    - grpc
    - grpcs
    - http
    - https
    - ws
    - wss
  - config:
      client_errors_severity: info
      custom_fields_by_lua: {}
      host: logs-01.loggly.com
      key: db039027-4439-4030-bc51-13ed30dd72c6
      log_level: info
      port: 514
      server_errors_severity: info
      successful_severity: info
      tags:
      - kong
      timeout: 10000
    enabled: true
    name: loggly
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: route
    path_handling: v0
    paths:
    - /abc
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
