_format_version: "3.0"
_workspace: WorkspaceA
consumers:
- keyauth_credentials:
  - key: secret
  username: admin
services:
- connect_timeout: 60000
  enabled: true
  host: 172.16.20.71
  name: admin-api
  plugins:
  - config:
      anonymous: null
      hide_credentials: true
      key_in_body: false
      key_in_header: true
      key_in_query: true
      key_names:
      - apikey
      run_on_preflight: true
    enabled: true
    name: key-auth
    protocols:
    - grpc
    - grpcs
    - http
    - https
    - ws
    - wss
  port: 8001
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: admin_route
    path_handling: v0
    paths:
    - /admin-api
    preserve_host: false
    protocols:
    - http
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
